modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0"

[[mods]]
modId="vulkanmod"
version="${version}"
displayName="Vulkan Reforged"
logoFile="assets/vulkanmod/Vlogo.png"
authors="Rindw"
credits="Rindw, and XCollateral (Original mod creator)"
description='''
Bring Vulkan to Minecraft!
'''

[[mixins]]
config="vulkanmod.mixins.json"

[[dependencies.vulkanmod]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.106,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vulkanmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"
