distanthorizons=2.1
create=0.5
xaerominimap=26
geckolib=4
playeranimator=2
architectury=13
cloth_config=15
curios=9
accessories=1
patchouli=87
balm=21
bookshelf=21
citadel=2
emotecraft=2
notenoughanimations=1
bettercombat=2
firstperson=2
customplayermodels=0.6
autohud=8
